### ISSUE TITLE
Ctrl-left and Ctrl-right do not function

### ISSUE THREAD

**Issue by ukch** [rhysd/NyaoVim#58] opened 2016-06-06 11:50 UTC
In vim I am used to using ctrl-left and ctrl-right to move left and right a word at a time (much like 'b' and 'w' in the default keybindings)

### Expected Behavior

ctrl-left to behave the same as 'b'
ctrl-right to behave the same as 'w'

### Actual Behavior

Neither key combination seems to have any function.

### Steps to Reproduce (including precondition)

* Open a buffer
* Navigate to the middle of a line of text
* Attempt to navigate using ctrl-left and ctrl-right

### Your Environment

- OS: Debian Sid
- NyaoVim version: 0.0.19
- `nvim` version: 0.1.3
- Keyboard layout: UK
- Linux: Window manager: GNOME Shell 3.20.2

### Additional Comments (if any)

I have tested using regular `nvim` (same config) and these key combinations work as expected.

**Comment by rhysd** [comment] 2016-08-10 01:35
I tried this and confirmed that NyaoVim sends `<C-Left>` and `<C-Right>` to `nvim` properly.  And cursor goes forward/backward by word properly in my environment.  From 0.0.19, some improvements were added related to key input handling.  So this issue may have gone.

I'll close this because I could not reproduce it.  But if there is still this issue, please ping me by commenting here or creating new issue.  Thank you for your report.

**Closed by rhysd** 2016-08-10 01:35 UTC
Labels: bug
